language: node_js
node_js:
- '6'
script:
- npm run test
- npm run lint-style
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install
after_success:
- npm run minify
notifications:
  email: false
addons:
  artifacts:
    paths:
    - $HOME/build/prestwick/webcharts-jqx-projectplan/min/example.min.js
    - $HOME/build/prestwick/webcharts-jqx-projectplan/min/example.min.js.map

